### ISSUE TITLE
Support NEP-6

### ISSUE THREAD

**Issue by gsmachado** [neo-project/neo-express#103]
While I understand the importance of having a `.neo-express` file with the complete specification of nodes, wallets, etc., in a single place (which is great for testing), I also think that neo-express should support NEP-6 (and maybe, NEP-2 also?).

I don't have a strong opinion on how this should be supported. This is totally up to discussion.

**Comment by devhawk** [comment]
There are a few commands that accept a wallet account name: `contract deploy`, `contract invoke`, `show balance[s]` and `transfer` being the most important ones. Should be possible to support path to a standard neo wallet file in those scenarios

**Comment by devhawk** [comment]
There are six commands that take at least one account as a command line argument :

* `contract deploy`
* `contract invoke`
* `oracle enable`
  * Note, by default only the `genesis` account can enable oracles
* `show balance`
* `show balances`
  * Note, both `show` commands that take an account argument only require the account address as a UInt160. Full wallet access (aka signing) is needed for all the non-`show` commands. Signing is not required for `show` commands
* `Transfer`

Today, each of these account arguments commands takes an Express Wallet name as a string, plus the string `genesis` to represent the multisig account shared across the consensus nodes. Consensus node express wallets have two accounts - one unique to the node plus the shared multisig consensus account. Non-consensus node express wallets never have more than a single, default account.

**Comment by devhawk** [comment]
Design Questions

1. Does express only need to support .json wallets or do I also need .db3 wallets as well? What about NEP-2 pass phrases?
2. Express wallet accounts are all single-sig except for the multi-sig account shared by the consensus nodes. JSON and DB3 based wallets have no such restriction. Building support for multi-account wallets and/or multi-sig accounts would require significant redesign and would be clunky to support on the command line. Express wallets only need a single string specified. JSON / DB3 wallets require at least two (path + password) plus potentially a third (account). Is Neo Express expected to support arbitrarily complex signing scenarios - including multi-sig - from the command line?
3. Show balance/balances commands don't require wallet signing support. Would it be good enough for these commands to simply accept a string encoded UInt160 (address format) rather than a full wallet (i.e. wallet + password)?

**Comment by wanglongfei88** [comment]
> Does express only need to support .json wallets or do I also need .db3 wallets as well? What about NEP-2 pass phrases?

I do not think it is not necessary for neo express to support .db3 since it is an old version of wallet which is mainly used by a few exchanges.  They are running their own neo nodes with .db3 wallet for safety and efficiency purpose. Other tools for development are not supporting or using .db3 anymore. But I think NEP-2 support will be a plus, because it is supported and used wildly in production. It is better to provide the same experience for development production. 

> Neo Express expected to support arbitrarily complex signing scenarios - including multi-sig - from the command line?

I do not have strong opinion towards supporting multi-sig from command line for neo express. But I do think it will be better to support nep6 wallet with name and password since it is the same way using wallet command anywhere else. 

 > Show balance/balances commands don't require wallet signing support. Would it be good enough for these commands to simply accept a string encoded UInt160 (address format) rather than a full wallet (i.e. wallet + password)?

I think definitely good enough. Anyone is able to check the wallet balances with a wallet address regardless with command line or other tools

**Comment by devhawk** [comment]
regarding password prompting: I need to build a way to determine if a password is going to be needed for a signing account. If the account is a valid file path, we treat it as a NEP6 wallet. If the account string can be base58 decoded into the appropriate length string, treat it as a NEP-2 encoded key. If either of these cases is true, but password hasn't been passed in (for non batch command) prompt the user for the password
