### ISSUE TITLE
"Object reference not set to an instance of an object" after neo-express contract invoke when running Runtime.CheckWitness(owner)

### ISSUE THREAD

**Issue by johnhoj** [neo-project/neo-express#12]
Using this simple test contract:

```
using Neo.SmartContract.Framework;
using Neo.SmartContract.Framework.Services.Neo;

public class NEP5 : SmartContract
{
    private static readonly byte[] owner = "AHWz3eLZL2Ymc8PKhQKzq9xDczWJf5K2ac".ToScriptHash();
    public static void Main()
    {
        bool isOwner = Runtime.CheckWitness(owner);
        if (isOwner) 
            Storage.Put(Storage.CurrentContext, "Hello", "World from owner");
        else
            Storage.Put(Storage.CurrentContext, "Hello", "World NOT from owner");

    }
}`
```

with the standard setup of the neo-blockchain-toolkit works in debug mode (returns always true as defined in the default.neo-express.json) but throws an exception when running invoke from the terminal as follows:

C:\...\NEP5>neo-express contract invoke NEP5 --account testWallet
Object reference not set to an instance of an object.
Usage: neo-express contract invoke [options] <Contract> <Arguments>

Running the same contract after just changing the Runtime.CheckWitness line by:

`bool isOwner = true;`

works well. So I conclude is the call to CheckWitness that fails.

running main works in Debug NeoCompiler and in the de

[NEP5.zip](https://github.com/neo-project/neo-blockchain-toolkit/files/3823378/NEP5.zip)

**Comment by devhawk** [comment]
There was a bug in neo-express - it was attaching coin references to the invocation transaction even though the transaction fee was below the free transaction threshold. commit a8752a32831ccbfe57a50c3e23a4a405293a150e resolves that issue. The fix is in v 0.9.85 of neo-express. There's another fix that needs to go into neo-express, so I'm not going to push this build to nuget.org, but there are [instructions for installing from our azure artifacts feed](https://github.com/neo-project/neo-express#install-preview-releases) in the repo readme if you want to test it right away.

However, what I've discovered is that neither neo-express nor neo-cli will sign the invocation transaction for this contract. @shargon suggested this might be the same issue as https://github.com/neo-project/neo-gui/issues/305. Since there are no signatures, that means that I don't think CheckWitness will behave as expected. @johnhoj please feel free to open a new bug in the [neo repo](https://github.com/neo-project/neo) if you have further issues with this.
