### ISSUE TITLE
FEATURE REQUEST: Have neo-express output deployment cost messages during a deploy?

### ISSUE THREAD

**Issue by roschler** [neo-project/neo-express#188]
Currently, when a `deploy` operation costs more gas than the deployer has, you get an "Insufficient gas" message.  It would be very helpful to add a mode to `neo-express` to make it output a running gas balance message to the console window as it executes the deploy operation.   Or perhaps have it emit to the console a message showing each cost affecting operation to the console window as the deployment progresses, so the developer can sum the amounts for themselves.  Even better would be a `verbose` mode where it outputted a stack trace with each message.

**Comment by devhawk** [comment]
it's not really feasible to echo this information to the console like you describe. It also wouldn't solve the issue @roschler hit this morning. The account @roschler was attempting to deploy from had 10000 GAS, the contract he was deploying cost about 23 GAS to deploy. However, Neo express wasn't providing correct GAS balance information to the wallet code constructing the deployment transaction - Instead, express was just using the default "max gas" value of 20 GAS, which is obviously not sufficient pay a 23 GAS fee.

Note, this only happened because @roschler was using offline mode. If the neo express node was running in the background, deployment would have gone thru RPC and the default max gas used by RPC is <checks notes> 10 million. 

(Don't ask me why the wallet uses 20 max gas by default and RPC uses 10 million - seems odd to me too)

Anyway, the PR #190 solves this issue by using the actual account GAS balance instead of the default 20 GAS.

If you want more details on deployment gas costs, you have options:

* The `show tx <txhash>` command prints the [transaction](https://docs.neo.org/docs/en-us/reference/rpc/latest-version/api/getrawtransaction.html) and [application log](https://docs.neo.org/docs/en-us/reference/rpc/latest-version/api/getapplicationlog.html) JSON to the console. The tx JSON includes the system and network fees (which when added together form the full GAS fee). Note, to get the value in fractional GAS, it needs to be divided by 10^8.
* you can trace out the deployment command (via the --trace option) and play it back in the debugger to see the gas cost
* you can also invoke the deployment operation directly in the debugger
