### ISSUE TITLE
fast forward preserving block time interval

### ISSUE THREAD

**Issue by gsmachado** [neo-project/neo-express#206]
As a developer, I would like to use the fast forward feature in unit/integration tests where the smart contract logic relies on block timestamps.

In this case, we would need that the block timestamp would follow a pre-configured block timestamp interval -- e.g., 15 seconds.

I imagine that this interval could be configured in neo-express. However, a default value could be set as well.

**Comment by devhawk** [comment]
The logic for fast forward timestamp calculation mirrors the timestamp calculation logic from DBFT module (cc @igormcoelho / @vncoelho).

From `ConsensusContext.MakePrepareRequest`:
``` cs
Block.Header.Timestamp = Math.Max(TimeProvider.Current.UtcNow.ToTimestampMS(), PrevHeader.Timestamp + 1);
```

Of course, the DBFT module uses timers to control when tokens are minted, so using UtcNow makes perfect sense. 

For fast forwarding, I could see using `PrevHeader.Timestamp + MillisecondsPerBlock` as the base timestamp for new blocks. However, express *MUST* ensure blocks don't get minted with out of order timestamps. I also think express *SHOULD* avoid minting FF blocks that have timestamps significantly out into the future.

For Online FF (i.e. executing `neoxp fastfwd` while the blockchain node is currently running), express can't use `PrevHeader.Timestamp + MillisecondsPerBlock` as a base timestamp since the running chain is already minting a "normal" block every `MillisecondsPerBlock`. For Online FF, I think express should exclusively use `PrevHeader.Timestamp + 1` as timestamp for FF blocks. Additionally, I think express should limit the number of blocks you can FF in online mode to 80% of `MillisecondsPerBlock` to avoid minting blocks while consensus round is underway.

For Offline FF, using `PrevHeader.Timestamp + MillisecondsPerBlock` seems like a simple choice, but it turns out to be more complex that it appears on the surface.

The `fastfwd` command reuses the same core offline block minting infrastructure that is used by `batch` and all the other commands modify blockchain state offline such as `transfer`, `contract deploy` and `contract invoke`. All these offline block minting commands (today) share the timestamp calculation logic. In other words, changing that timestamp logic affects all the offline commands.

I don't know about other developers, but I use `neoxp batch` with `--reset` to configure neo-express in my contract projects. `batch` was specifically designed to be as fast as possible so it could conceivably be run every time you build the contract, so you always have an express blockchain with the latest version of the contract ready to go. 

If we change the offline timestamp logic to `PrevHeader.Timestamp + MillisecondsPerBlock`, this means the first offline block minted will have a timestamp of `GenesisBlock.Timestamp + MillisecondsPerBlock`. Obviously, we can mint a lot of offline blocks using `MillisecondsPerBlock` starting from `GenesisBlock.Timestamp`. However, I don't know how that might affect the smart contract logic you are thinking about @gsmachado. Would such logic get broken using timestamps from 2016? 

Also, express is not going to modify the algorithm that DBFT module uses to mint blocks when running. So as soon as you mint a single block with `neoxp run` you'll have a recent UtcNow based timestamp. Under the current model, the genesis block timestamp is way in the past but all blocks after that have a current timestamp. With this newer approach, any offline blocks that get minted before first run will also have distant past timestamps. 

Frankly, as long as timestamps are monotonically increasing, I don't really care what the logic is to calculate them. But before we change the existing logic, we need to understand the ramifications

**Comment by devhawk** [comment]
The more I think about this, the more I think it's a bad idea to depend on block timestamps being regularly `MillisecondsPerBlock` apart in your test code. These timestamps will simply never be consistent in neo express because of express offline block minting in general and FF blocks in particular.

@gsmachado, I would recommend some kind of test-specific abstraction for contract logic that depends on block timestamps consistency. As I'm sure you're aware, time testing abstractions are common in non-blockchain code. As an example, see [Reactive Extensions' TestScheduler](http://introtorx.com/Content/v1.0.10621.0/16_TestingRx.html#TestingRx) for use during tests. 

I was helping @roschler recently with some code he's working on that uses the [`Nep11Token` class](https://github.com/neo-project/neo-devpack-dotnet/blob/master/src/Neo.SmartContract.Framework/Nep11Token.cs) from the Smart Contract Framework. In the Nep11Token code, minted NFTs get an ID generated based on the contract hash of the token contract (i.e. `Runtime.ExecutingScriptHash`). Since the script hash changes on every code change, the minted token IDs change on every redeployment of new code, which complicates testing dramatically.

His solution was to build a `isNeoExpress` method that compares the blockchain network value (i.e. `System.Runtime.GetNetwork`) against known network values for mainnet / testnet. This let him swap in a different token ID generation algorithm when running on NeoExpress that is deterministic across code changes. This works because NeoExpress randomly generates a network value on `neoxp create` and explicitly checks to make sure the randomly generated value is not a known network value like N3 mainnet or testnet. 

@gsmachado I'm thinking your timing logic could use a similar mechanism to avoid depending on consistently spaced timestamps.

Another way to handle scenarios like this is to code that is conditionally compiled. C# doesn't have a full preprocessor like C++, but it does support [#if conditional compilation directives](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/preprocessor-directives#conditional-compilation) (though I *don't* know if such directives are supported by NCCS). As much as I like @roschler's approach, I think it would be even better with conditional compilation so that the code only checks `isNeoExpress` when `#if DEBUG` and *always* uses the standard `ExecutingScriptHash` token generation algorithm when running in release mode. Since you pay GAS per statement, seems worth it to remove the `isNeoExpress` check in the production code that gets deployed to mainnet.


Does Java / neow3j have support for some kind of conditional compilation?

**Comment by gsmachado** [comment]
> I also think express SHOULD avoid minting FF blocks that have timestamps significantly out into the future.

Why not? That's exactly what we need. 😄 

**After thinking a bit better based on your answers and having an internal discussion with @csmuller and @mialbu, let me change what I initially requested in this issue:**

**We would say that, for 99% of tests targeting time-dependent smart contracts, devs would not care if the interval between blocks is consistently spread (i.e., the time interval between block 1 and block 2 could be 10 seconds, but between block 2 and block 3 could be 1 minute). So, `MillisecondsPerBlock` could serve just as a best-effort parameter or something like this. The feature of traveling to a specific time point in the future is way more important than a consistent `MillisecondsPerBlock` interval.**

So, about this line:

```csharp
Block.Header.Timestamp = Math.Max(TimeProvider.Current.UtcNow.ToTimestampMS(), PrevHeader.Timestamp + 1);
```

As far as we understood, if neo-express mints/sets new FF blocks with timestamps in the future, then, as soon as the consensus kicks in for the next block, the timestamp of the next block would be `PrevHeader.Timestamp + 1`. So, we assume nothing would need to be changed in the DBFT mechanism...

> If we change the offline timestamp logic to `PrevHeader.Timestamp + MillisecondsPerBlock`, this means the first offline block minted will have a timestamp of `GenesisBlock.Timestamp + MillisecondsPerBlock`. Obviously, we can mint a lot of offline blocks using `MillisecondsPerBlock` starting from `GenesisBlock.Timestamp`. However, I don't know how that might affect the smart contract logic you are thinking about @gsmachado. Would such logic get broken using timestamps from 2016?

For time-dependent smart contracts, yes, it could have an impact... but not necessarily. If we have a way to "time travel" from 2016 to 2023, for example, to simulate that a smart contract action can be accomplished, it's fine. No worries.

> Does Java / neow3j have support for some kind of conditional compilation?

At the moment we don't plan to have any conditional compilation in neow3j... although, it's an interesting feature.

But, let me give you an example from the Ethereum world (also applied to tools in other chains).

If you're using Ganache/Hardhat (great tools, BTW), you have [special testing methods](https://hardhat.org/hardhat-network/reference/#special-testing-debugging-methods) (also exposed as JSON-RPC).

In special, the ones I already used in Ethereum contracts are `evm_increaseTime`, `evm_setIntervalMining`, and `evm_setNextBlockTimestamp`.

These methods are super convenient for developers.

Instead of changing the smart contract's code and/or dealing with risks at the compiler level, why not provide a way to "manipulate" the privatenet chain in order to get the conditions (even if close to unreal) to satisfy tests? This seems a better and superior way to me -- given that we see the same design pattern in tooling of other chains as well. It's developers' responsibility to know what they're doing with the options hardhat/ganache/neo-express provide. Don't you think?

**Comment by gsmachado** [comment]
Given that I changed my mind and requested just a time-travel feature for block.timestamp, I decided to create a new issue: https://github.com/neo-project/neo-express/issues/207. It's a simpler one and would not require to drastically change things, IMHO.

@devhawk @csmuller let's close this one and further discuss in #207.
