### ISSUE TITLE
Unable to get genesis token balances for reset blockchains

### ISSUE THREAD

**Issue by gsmachado** [neo-project/neo-express#220]
Check this:

```
> neoxp show balance gas genesis
GAS (0xd2a4cff31913016155e38e474a2c06d08be276cf)
                                                  balance: 52000000

> neoxp show balance neo genesis
NEO (0xef4073a0f2b305a38ec4050e4d3d28bc40ea63f5)
                                                  balance: 100000000

> neoxp show balances genesis
No balances for genesis
```

This affects the whole Neo Blockchain Toolkit, since it heavily relies on neo-express.

**Comment by gsmachado** [comment]
![image](https://user-images.githubusercontent.com/2124276/160887303-365a64f3-8f28-46d4-947c-9bfd76c7cb3a.png)

**Comment by devhawk** [comment]
The Express RPC server implementation of [getnep17balances](https://docs.neo.org/docs/en-us/reference/rpc/latest-version/api/getnep17balances.html) builds a list of tokens by iterating thru the list of Transfer notifications fired by transactions in the chain. If there are no Transfer notifications for a given token - as would be the case for a recently created/reset chain - then the RPC method never checks the current balances of any token. Which is what we're seeing in this issue.

Note, there's likely a similar issue in the standard TokenTracker module. But since mainnet and testnet are not getting reset to genesis like express chains are, not likely an issue
