### ISSUE TITLE
No CustomContract and other NEO witness scopes support

### ISSUE THREAD

**Issue by someRandomDamn** [neo-project/neo-express#236]
![image](https://user-images.githubusercontent.com/93192858/176406342-edeba1c0-3063-4022-abf2-7ac65c382db4.png)

**Comment by devhawk** [comment]
Express `contract invoke/run` commands are not intended to be the primary invocation mechanism for contracts. Submitting transactions via RPC using DevTracker and/or a custom dapp are also possibilities.

Express supports `None`, `CalledByEntry` and `Global` scopes because they require no additional data. The remaining `WitnessScope` options require additional information that would be difficult to pass on the command line:

* `CustomContracts` requires a collection of contract hashes
* `CustomGroups` requires a collection of public keys
* `WitnessRules` requires a collection of rule trees

**Comment by devhawk** [comment]
This could be better supported in devtracker. tracked by https://github.com/ngdenterprise/neo3-visual-tracker/issues/92
