### ISSUE TITLE
Contract run calls within a batch file may be passed the wrong arguments

### ISSUE THREAD

**Issue by EdgeDLT** [neo-project/neo-express#284]
There is an issue that affects `contract run` when it is used multiple times within a command batch. If the targeted contract method has no arguments, it may instead be passed arguments from the previous `contract run` call to a different method within the same batch.

Example:

```
transfer 10000 gas genesis bob
contract deploy ./smartwallet.nef bob
contract run gastoken transfer @bob #smartwallet 1234567890 null -a bob -w CalledByEntry
contract run smartwallet sendAsset #gastoken @charlie 321 null -a bob -w CalledByEntry
transfer 1 neo genesis #smartwallet
contract run smartwallet claimGas -a bob -w CalledByEntry  // <-- will be passed the args #gastoken @charlie 321 null
```

```
PUSHDATA1 null
PUSHINT16 321
PUSHDATA1 0x01cd81e566450ac412a87a5e604691e8050ce09b
PUSHDATA1 0xd2a4cff31913016155e38e474a2c06d08be276cf
PUSH4
PACK
PUSH15
PUSHDATA1 claimGas
PUSHDATA1 0x9c0d35b58fc4dd3c0c590a5ede5434c1dc9762ea
SYSCALL System.Contract.Call
```

**Comment by devhawk** [comment]
This is a bug in the command line processing library Express uses. 

In `BatchCommand.ExecuteAsync`, we create an instance of `CommandLineApplication<BatchFileCommands>` and use it to process each non-comment line in the batch file. As part of processing each line, the library binds the arguments to a strongly typed model instance, the properties of which are then passed to other methods to do the requested processing.

This model instance appears to be reused between calls. Since the claimGas call doesn't have any arguments, the command parsing skips binding the empty argument array to the strongly typed Arguments property of the model instance. Thus, the old value from the previous `contract run` call are never cleared.

We can either create a new `CommandLineApplication<BatchFileCommands>` instance for each line of the batch file or we can use the command's `.Arguments` property (not the model's `.Arguments` property - confusingly in this case the model property is also named Arguments).

**Comment by cschuchardt88** [comment]
Its looks like this is fixed Can you confirm?

Im using
```text
transfer 10000 gas genesis node1
contract deploy ./sc/LoomsCoin.nef node1
contract run gastoken transfer @node1 #LoomsCoin 1 null -a node1
transfer 1 neo genesis @LoomsCoin
contract run LoomsCoin claimGas -a node1
```
