### ISSUE TITLE
Make 'Address' the default representation for UInt160 types

### ISSUE THREAD

**Issue by lock9** [neo-project/neo-express#296]
Problem: 
- UInt160 representation needs to be revised. It's impossible to distinguish the correct value due to differences in endianness and encoding format (hex). 
- There are inconsistencies across the CLI, configuration files and SDKs. 

Proposed Solution:
- Make 'Address' the default representation for UInt160 types (input and output)

Related:
https://github.com/neo-project/neo-express/issues/285
https://github.com/neo-project/neo-express/issues/276
https://github.com/neo-project/neo-express/issues/270

Please check Roman's message here:
https://github.com/neo-project/neo-express/issues/276#issuecomment-1570501911

**Comment by ixje** [comment]
> Problem:
> 
> * UInt160 representation needs to be revised. It's impossible to distinguish the correct value due to differences in endianness and encoding format (hex).

Can you be more specific and give examples?

> * There are inconsistencies across the CLI, configuration files and SDKs.

An example of this is https://github.com/neo-project/neo-express/issues/270 but that seems tool specific and I don't understand why "everything" needs to be become an address as proposed below because of that.

> Proposed Solution:
> 
> * Make 'Address' the default representation for UInt160 types (input and output)

In general I'm against smart conversion because historically I've seen tools trying to be smart by interpreting any byte array with a length of 20 as a UInt160, while the data I was passing simply happened to just be 20 bytes. It was impossible to turn off. To that same extend if I want to log or return a UInt160 from a smart contract, I don't want it to automatically be represented as an address string. I can convert that myself if that's the format I want.

Note I do see value in also accepting a NeoAddress in places where a UInt160 is expected, because these values often come from explorers or wallets. To clarify "places"; I mean in CLI commands/invoke files/SC debug configurations expecting contract hashes.

**Comment by lock9** [comment]
>  I've seen tools trying to be smart by interpreting any byte array with a length of 20 as a UInt160, while the data I was passing simply happened to just be 20 bytes. It was impossible to turn off

Exactly. The only way to know if they user is trying to send an address or just a byte array, is by using some kind of formatting.

>Can you be more specific and give examples?

Your example is good: Currently, it's not possible to know if that hex string is an scripthash (UInt160) or not. Or if it should be reversed. 

If the parameter type is UInt160, why can't we use address representation? My concern is that not only we already get confused with all this 'reverse' stuff, imagine what will happen once the new EVM sidechain. Hex are universal, while addresses are domain specific

**Comment by cschuchardt88** [comment]
Best way is to check for byte array length of 20 and than do `Base58.CheckEncode`

**Comment by ixje** [comment]
> If the parameter type is UInt160, why can't we use address representation? 

My problem is that you seem to request enforcing NeoAddress usage everywhere, whereas I believe the end user should be able to choose. I work with script hashes 99% of the time and rarely with NeoAddress. Why would I need to be forced to convert a NeoToken script hash to a NeoAddress before I can use it?

There are already some rules regarding input which at least neo-debugger adheres to
* a string starting with `0x`, the remainder is interpreted as a byte array
* a string starting with `#0x`, the reaminder is interpreted as a `UInt160` or `UInt256` depending on the size of the data
* a string start with `@`, the remainder is interpreted as a `NeoAddress` and will be converted to a `UInt160`

I believe the goal should be to make sure that neo-express `.invoke-file`s and the CLI accept the same input as above so that all C# tools (that build on the blockchaintoolkit lib) work the same way.

**Comment by lock9** [comment]
>I work with script hashes 99% of the time and rarely with NeoAddress

What are these hashes, if not addresses?

**Comment by cschuchardt88** [comment]
`0xfffdc93764dbaddd97c48f252a53ea4643faa3fd` is a scripthash in neo programing we use them in that format which is `UInt160`

**Comment by lock9** [comment]
>0xfffdc93764dbaddd97c48f252a53ea4643faa3fd is a scripthash in neo programing we use them in that format which is UInt160
>
>Neo Addresses are only for sending to users and transfering funds.

Addresses are just script hashes using a different encoding

**Comment by ixje** [comment]
> What are these hashes, if not addresses?

Contract hashes. We can argue that a contract hash can also be turned into an address, but I only associated NeoAddresses with the source and destination arguments of NEP-11/NEP-17 transfers. I have yet to see anyone instantly recognise this address `NiHURyS83nX2mpxtA7xq84cGxVbHojj5Wc` but I'm pretty sure most will recognise this `0xef4073a0f2b305a38ec4050e4d3d28bc40ea63f5`. This obviously depends on if you're just a wallet user or if you are a developer.

**Comment by lock9** [comment]
I agree that they are both recognizable, but there is a difference:
You can identify what is an N3 script hash and what is not. The first one is domain-specific, Neo N3. The second one can be anything.

**Comment by ixje** [comment]
If I didn't know that all Neo 3 addresses start with `N` then `NiHURyS83nX2mpxtA7xq84cGxVbHojj5Wc` could have also been a Bitcoin address or some weird encoded data specific to a contract.

Back on topic; the preferred default representation is use-case/user specific and I therefore think it should be up to the user to decide what it should be.

**Comment by lock9** [comment]
> If I didn't know that all Neo 3 addresses start with `N` then `NiHURyS83nX2mpxtA7xq84cGxVbHojj5Wc` could have also been a Bitcoin address or some weird encoded data specific to a contract.

I didn't understand this, could you explain?

**Comment by cschuchardt88** [comment]
>Back on topic; the preferred default representation is use-case/user specific and I therefore think it should be up to the user to decide what it should be.

This isn't the case. It really depends on where the `UInt160` hash or N3 Address is. Programming its in ScriptHash format. For people sending funds it would be N3 address. 

I think it's a matter of people learning ScriptHash vs N3 address when programming.

**Comment by ixje** [comment]
> This isn't the case. It really depends on where the UInt160 hash or N3 Address is.

Are you not contradicting yourself here?

> Programming its in ScriptHash format. For people sending funds it would be N3 address.

That is your view. My view is that I **always** use a script hash for the contract when sending funds and **never** the N3 address of a contract. So that basically shows that it is a user preference.

**Comment by chenzhitong** [comment]
I see this is still being discussed and not agreed upon. Does this issue need to be discussed further?

**Comment by cschuchardt88** [comment]
No, just change the `scripthash` to neo3 `address`

**Comment by ixje** [comment]
> No, just change the `scripthash` to neo3 `address`

What does that mean? Which part of the code or interface are we affecting here?

**Comment by cschuchardt88** [comment]
> > No, just change the `scripthash` to neo3 `address`
> 
> What does that mean? Which part of the code or interface are we affecting here?

The output that is displayed to the end user, in `console`.

**Comment by ixje** [comment]
Can you be explicit and link the place in the code? 
Atm I'm mostly concerned that this isn't going to make the UX terrible for interacting/working with contracts.
