### ISSUE TITLE
Allow devtracker to programmatically detect whether -f will be needed when restoring a checkpoint

### ISSUE THREAD

**Issue by djnicholson** [neo-project/neo-express#38]
Either:
a) Add a custom RPC endpoint for restoring checkpoints that returns an object indicating success or failure (and whether the failure was due to blockchain data already existing and -f not being supplied)
b) Add an option to make the existing restore command return JSON instead of text (and do not block waiting for the user to press 'q' when there is a failure)

**Comment by devhawk** [comment]
I don't see how we can add a custom RPC endpoint for this scenario as neo express can't be running during restore anyway.

I've fixed the pager issue for NeoExpress N3 (i.e. the `q` issue).

If -f is not supplied, `You must specify force to restore a checkpoint to an existing blockchain.` gets printed to the console. I'm not sure what more wrapping that in JSON will do.

Reassigning to @djnicholson . Close if this issue is no longer relevant

**Comment by djnicholson** [comment]
When I opened this I think I was under the impression that restore-while-running was supported as long as an additional parameter was required.

No longer relevant.
